version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionString=server=host.docker.internal;port=5432;database=catalog;uid=postgres;password=Nataliia123;
    depends_on:
      - postgres
    ports:
      - 5002:5002
  web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogUrl=http://host.docker.internal:5002/api/v1/catalogbff
    depends_on:
      - catalog.api
    ports:
      - 5001:5001
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nstasiukova@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: Nataliia123
      POSTGRES_DB: catalog
    ports:
      - 5432:5432
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4